version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_bai12
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana_bai12
    ports:
      - "3001:3000" # Grafana chạy ở cổng 3001
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter_bai12
    ports:
      - "9100:9100"