version: '3.8'

services:
  # 1. Dịch vụ MongoDB
  mongo-db:
    image: mongo:latest
    container_name: mongodb_vinh
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # 2. Ứng dụng Node.js
  node-app:
    build: ./app
    container_name: node_app_vinh
    ports:
      - "8086:3000"
    depends_on:
      mongo-db:
        condition: service_healthy # Chỉ chạy khi mongo-db đã vượt qua healthcheck
    networks:
      - app-network

networks:
  app-network:
    driver: bridge