version: '3.8'

services:
  # Dịch vụ Node.js
  app-node:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    depends_on:
      - db-mysql

  # Dịch vụ MySQL
  db-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"