services:
  db:
    image: mysql:5.7          # WordPress tương thích rất tốt với bản 5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"             # Truy cập WordPress qua cổng 8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword

      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:                    # Lưu trữ dữ liệu để không bị mất khi restart