version: '3.8'

services:
  # Dịch vụ PostgreSQL
  db-postgres:
    image: postgres:15
    container_name: postgres_bai11
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Công cụ quản lý Adminer
  adminer-tool:
    image: adminer
    container_name: adminer_bai11
    restart: always
    ports:
      - "8083:8080" # Yêu cầu chạy cổng 8083
    depends_on:
      - db-postgres